### ISSUE TITLE
afl.rs works on M1

### ISSUE THREAD

**Issue by andrewgazelka** [rust-fuzz/book#30]

**Comment by frewsxcv** [comment]
https://github.com/rust-fuzz/book/commit/16566ed57748b1353b9c7a13c0e2fd26572bffbe

**Comment by andrewgazelka** [comment]
@frewsxcv this does not close this issue

**Comment by frewsxcv** [comment]
How come?

**Comment by frewsxcv** [comment]
Oh I linked to the wrong commit: https://github.com/rust-fuzz/book/commit/81ceff8ad4ed9c9991bacaddbfb133c3e661360e
